### ISSUE TITLE
Issue with Api.ai in default mode

### ISSUE THREAD

**Issue by michaelulin** [botpress/botpress-api.ai#13]
After enabling the API.AI module in default mode, I receive the following error. I'm unable to access the appended data from API.AI. This is not an issue with the wit.ai module.

error: Unhandled Rejection in Promise:  Promise {
  <rejected> ReferenceError: shortUserId is not defined
    at incomingMiddleware (/home/michael/testbot/node_modules/botpress-api.ai/bin/webpack:/src/index.js:93:25)
    at exec (/home/michael/testbot/node_modules/mware/index.js:50:23)
    at next (/home/michael/testbot/node_modules/mware/index.js:60:9)
    at incomingMiddleware (/home/michael/testbot/node_modules/botpress-analytics/bin/webpack:/src/index.js:22:12)
    at exec (/home/michael/testbot/node_modules/mware/index.js:50:23)
    at next (/home/michael/testbot/node_modules/mware/index.js:60:9)
    at processIncoming (/home/michael/testbot/node_modules/botpress/lib/webpack:/src/umm/index.js:203:5)
    at exec (/home/michael/testbot/node_modules/mware/index.js:50:23)
    at next (/home/michael/testbot/node_modules/mware/index.js:60:9)
    at /home/michael/testbot/node_modules/botpress/lib/webpack:/src/listeners.js:58:9
    at exec (/home/michael/testbot/node_modules/mware/index.js:50:23)
    at Function.run (/home/michael/testbot/node_modules/mware/index.js:63:7)
    at Object.dispatch (/home/michael/testbot/node_modules/botpress/lib/webpack:/src/middlewares.js:45:10)
    at Object.sendIncoming (/home/michael/testbot/node_modules/botpress/lib/webpack:/src/middlewares.js:159:29)
    at /home/michael/testbot/node_modules/botpress-messenger/bin/webpack:/src/incoming.js:152:22
    at <anonymous> } Reason: ReferenceError: shortUserId is not defined
    at incomingMiddleware (/home/michael/testbot/node_modules/botpress-api.ai/bin/webpack:/src/index.js:93:25)
    at exec (/home/michael/testbot/node_modules/mware/index.js:50:23)
    at next (/home/michael/testbot/node_modules/mware/index.js:60:9)
    at incomingMiddleware (/home/michael/testbot/node_modules/botpress-analytics/bin/webpack:/src/index.js:22:12)
    at exec (/home/michael/testbot/node_modules/mware/index.js:50:23)
    at next (/home/michael/testbot/node_modules/mware/index.js:60:9)
    at processIncoming (/home/michael/testbot/node_modules/botpress/lib/webpack:/src/umm/index.js:203:5)
    at exec (/home/michael/testbot/node_modules/mware/index.js:50:23)
    at next (/home/michael/testbot/node_modules/mware/index.js:60:9)
    at /home/michael/testbot/node_modules/botpress/lib/webpack:/src/listeners.js:58:9
    at exec (/home/michael/testbot/node_modules/mware/index.js:50:23)
    at Function.run (/home/michael/testbot/node_modules/mware/index.js:63:7)
    at Object.dispatch (/home/michael/testbot/node_modules/botpress/lib/webpack:/src/middlewares.js:45:10)
    at Object.sendIncoming (/home/michael/testbot/node_modules/botpress/lib/webpack:/src/middlewares.js:159:29)
    at /home/michael/testbot/node_modules/botpress-messenger/bin/webpack:/src/incoming.js:152:22
    at <anonymous>

**Comment by slvnperron** [comment]
Thanks Michael, the issue has been fixed and will be deployed by EOD in the upcoming patch release of this module

**Comment by michaelulin** [comment]
Thanks!
